### ISSUE TITLE
Breaking change in websocket subscriptions December 2022

### ISSUE THREAD

**Issue by Skjal** [flopp999/Tibber-Domoticz#54]
seems like Tibber has changed their websockets so that Domoticz cant connect anymore to the api. here is the link from tibber https://developer.tibber.com/docs/overview#breaking-websocket-change. would you please have a look at this and update the plugin?

**Comment by flopp999** [comment]
I will have a look at and see if I can fix it

**Comment by flopp999** [comment]
I now have a working example, so I should be able to fix this so it will work

**Comment by me-processware** [comment]
> I now have a working example, so I should be able to fix this so it will work

i will buy you a few extra cups of coffee :) it save's me money because i can charge my battery when the price is low

**Comment by flopp999** [comment]
I have now updated so it shall work.

Can you update your plugin and try it?
Thanks

**Comment by Skjal** [comment]
Will do as soon as I get the chance.

tir. 20. des. 2022, 13:51 skrev flopp999 ***@***.***>:

**Comment by me-processware** [comment]
i have installed the plugin but only 13 custom sensors are working:

i have data from:

power
voltagePhase1
voltagePhase3
voltagePhase2
powerProduction
currentL1
currentL2
currentL3
Current Price
Current Price incl. fee
Mean Price
Minimum Price
Maximum Price

but not from:

minPowerProduction
signalStrength
minPower
maxPower
maxPowerProduction
lastMeterProduction
lastMeterConsumption
accumulatedConsumption
accumulatedProduction
accumulatedConsumptionLastHour
accumulatedProductionLastHour
accumulatedCost
accumulatedReward
averagePower

2022-12-21 01:48:48.700 tibber: Live power updated
2022-12-21 01:48:58.211 tibber: Traceback (most recent call last):
2022-12-21 01:48:58.211 File "/opt/domoticz/userdata/plugins/Tibber-Domoticz/plugin.py", line 338, in LivePowerEvery
2022-12-21 01:48:58.211 async with Client(transport=WebsocketsTransport(url="wss://api.tibber.com/v1-beta/gql/subscriptions", init_payload={"token": self.AccessToken}, headers={"User-Agent": "user_agent"}, ping_interval=10 ) ) as session:
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/client.py", line 660, in __aenter__
2022-12-21 01:48:58.211 return await self.connect_async()
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/client.py", line 634, in connect_async
2022-12-21 01:48:58.211 await self.transport.connect()
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets_base.py", line 512, in connect
2022-12-21 01:48:58.211 await self._initialize()
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets.py", line 157, in _initialize
2022-12-21 01:48:58.211 await self._send_init_message_and_wait_ack()
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets.py", line 154, in _send_init_message_and_wait_ack
2022-12-21 01:48:58.211 await asyncio.wait_for(self._wait_ack(), self.ack_timeout)
2022-12-21 01:48:58.211 File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
2022-12-21 01:48:58.211 return fut.result()
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets.py", line 131, in _wait_ack
2022-12-21 01:48:58.211 answer_type, answer_id, execution_result = self._parse_answer(init_answer)
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets.py", line 430, in _parse_answer
2022-12-21 01:48:58.211 return self._parse_answer_apollo(json_answer)
2022-12-21 01:48:58.211 File "/usr/local/lib/python3.7/dist-packages/gql/transport/websockets.py", line 403, in _parse_answer_apollo
2022-12-21 01:48:58.211 raise TransportServerError(f"Server error: '{repr(error_payload)}'")
2022-12-21 01:48:58.211 gql.transport.exceptions.TransportServerError: Server error: '{'message': 'Prohibited connection!'}'
2022-12-21 01:48:58.211
2022-12-21 01:48:58.211 tibber: <class 'gql.transport.exceptions.TransportServerError'>
2022-12-21 01:49:09.315 tibber: Live power updated

**Comment by flopp999** [comment]
Please try again with version 1.20

**Comment by flopp999** [comment]
version 1.22 should work

**Comment by me-processware** [comment]
> version 1.22 should work

thanks it works :) noticed the plugin stopped today @ 10:59 but i thought it was a api limit on my side. thanks for the update
